import {SongInterface} from "../interfaces/song.interface";

export const fakeSong: SongInterface = {
    title: "I was just a kid",
    artist: "Nothing but thieves",
    genres: ["rock", "indie"],
}
export const fakeSong2: SongInterface = {
    title: "Have a cigar",
    artist: "Pink Floyd",
    genres: ["rock", "psychedelic"],
}


export const fakeLyrics = [
    "I was just a kid",
    "I needed answers",
    "I found a screenPromised adventure",
    "Just as I thought",
    "I had it all",
    "I pulled the trigger",
    "And nothing happened",
    "",
    "I was in a dream",
    "I was in heaven",
    "I saw a god",
    "I had a question",
    "Opened my eyes",
    "Fell out the sky",
    "Tried to remember",
    "But there was nothing",
    "",
    "Then you gave me something",
    "Something to believe in",
    "Yeah, you gave me something",
    "Something to believe in, oh",
    "",
    "′Cause I was just a kid",
    "I was just a kid",
    "How'd it get like this?",
    "",
    "And the story ends",
    "But life goes on so",
    "Like those before",
    "And those to follow",
    "Just when you thought",
    "You knew it all",
    "You find another",
    "And then it happens",
    "",
    "′Cause you gave me something",
    "Something to believe in",
    "Yeah, you gave me something",
    "Something to believe in",
    "",
    "'Cause I was just a kid",
    "I was just a kid",
    "'Cause I was just a kid",
    "And you gave me something",
    "Gave my life a meaning",
    "Yeah, you gave me something",
    "Something to believe in",
    "′Cause I want something to believe in",
    "Yeah, I want something to believe in"
];